"""Tests for central period-lock middleware and PDF download guard."""

import json
import os
import tempfile
import unittest
from types import SimpleNamespace
from unittest.mock import patch

from flask import Flask

from utils.pdf_download_guard import (
    read_pdf_download_meta,
    verify_pdf_download_allowed,
    write_pdf_download_meta,
)
from utils.period_lock_guard import (
    check_period_lock_contexts,
    is_period_lock_exempt_path,
    period_lock_contexts_from_request,
    register_period_lock_middleware,
)


class PeriodLockGuardHelpersTests(unittest.TestCase):
    def test_exempt_paths(self):
        self.assertTrue(is_period_lock_exempt_path("/api/auth/login"))
        self.assertTrue(is_period_lock_exempt_path("/api/generate-pdf"))
        self.assertTrue(is_period_lock_exempt_path("/api/periods/abc/open"))
        self.assertTrue(is_period_lock_exempt_path("/api/export/excel"))
        self.assertFalse(is_period_lock_exempt_path("/api/universal/approve"))

    @patch("utils.period_lock_guard.check_session_period_unlocked")
    @patch("utils.period_lock_guard._load_session")
    def test_check_contexts_blocks_locked_session(self, mock_load, mock_check):
        mock_load.return_value = SimpleNamespace(metadata={"period_id": "p1"})
        mock_check.return_value = (False, "FY 2025 is locked.")
        allowed, msg = check_period_lock_contexts([
            {"session_id": "sess-1", "document_type": "budget_report", "period_id": None},
        ])
        self.assertFalse(allowed)
        self.assertIn("locked", msg.lower())

    @patch("utils.period_lock.period_model.get_period")
    def test_check_contexts_blocks_locked_period_id(self, mock_get):
        mock_get.return_value = SimpleNamespace(
            id="p1", name="Q1", is_locked=True, metadata={"is_locked": True}
        )
        allowed, msg = check_period_lock_contexts([
            {"session_id": None, "document_type": None, "period_id": "p1"},
        ])
        self.assertFalse(allowed)


class PdfDownloadGuardTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        for name in os.listdir(self.tmp):
            path = os.path.join(self.tmp, name)
            if os.path.isfile(path):
                os.remove(path)
        os.rmdir(self.tmp)

    @patch("utils.pdf_download_guard.resolve_pdf_availability")
    def test_verify_uses_meta_and_availability(self, mock_avail):
        mock_avail.return_value = {"can_generate_pdf": True, "reason": ""}
        write_pdf_download_meta(
            self.tmp,
            "report.pdf",
            session_id="sess-1",
            document_type="balance_sheet",
            period_id="p1",
            user_id="user-1",
        )
        allowed, err = verify_pdf_download_allowed(
            self.tmp, "report.pdf", user_id="user-1"
        )
        self.assertTrue(allowed)
        self.assertEqual(err, "")
        mock_avail.assert_called_once()

    @patch("utils.pdf_download_guard.resolve_pdf_availability")
    def test_verify_allows_other_user_when_period_locked(self, mock_avail):
        """FM (or any download_pdf user) may download a PDF generated by the CFO."""
        mock_avail.return_value = {"can_generate_pdf": True, "reason": ""}
        write_pdf_download_meta(
            self.tmp,
            "report.pdf",
            session_id="sess-1",
            document_type="balance_sheet",
            period_id="p1",
            user_id="owner",
        )
        with open(os.path.join(self.tmp, "report.pdf"), "wb") as fh:
            fh.write(b"%PDF-1.4")
        allowed, err = verify_pdf_download_allowed(
            self.tmp, "report.pdf", user_id="other"
        )
        self.assertTrue(allowed, err)

    def test_meta_roundtrip(self):
        write_pdf_download_meta(
            self.tmp,
            "x.pdf",
            session_id="s",
            document_type="budget_report",
            period_id=None,
            user_id="u",
        )
        meta = read_pdf_download_meta(self.tmp, "x.pdf")
        self.assertEqual(meta["session_id"], "s")
        self.assertEqual(meta["document_type"], "budget_report")


class PeriodLockMiddlewareTests(unittest.TestCase):
    def test_middleware_blocks_locked_submit(self):
        app = Flask(__name__)
        app.config["TESTING"] = True
        register_period_lock_middleware(app)

        @app.route("/api/universal/submit-for-review", methods=["POST"])
        def submit():
            return jsonify({"success": True})

        with patch(
            "utils.period_lock_guard.check_period_lock_contexts",
            return_value=(False, "Period locked."),
        ):
            client = app.test_client()
            res = client.post(
                "/api/universal/submit-for-review",
                json={"session_id": "s1", "document_type": "budget_report"},
            )
        self.assertEqual(res.status_code, 403)
        body = res.get_json()
        self.assertTrue(body.get("period_locked"))


if __name__ == "__main__":
    unittest.main()
