"""
SADPMR Financial Reporting System - Fund Accounting Models
GRAP 18 compliant multi-dimensional fund accounting system
"""

from datetime import datetime
from typing import Dict, List, Optional, Any
import pandas as pd

class FundAccountingModel:
    """Fund accounting model for GRAP 18 compliance"""
    
    def __init__(self):
        self.fund_structure = self._initialize_fund_structure()
        self.department_structure = self._initialize_department_structure()
        self.function_structure = self._initialize_function_structure()
        self.fund_tags = {}
        self.segment_mappings = {}
        
    def _initialize_fund_structure(self) -> Dict[str, Any]:
        """Initialize fund structure for GRAP 18 compliance"""
        return {
            'government_funds': {
                'code': 'GF',
                'name': 'Government Funds',
                'description': 'Funds provided by government for specific purposes',
                'restrictions': 'Highly restricted - can only be used for specified purposes',
                'reporting_required': True,
                'audit_required': True
            },
            'donor_funds': {
                'code': 'DF',
                'name': 'Donor Funds',
                'description': 'Funds provided by donors with specific conditions',
                'restrictions': 'Restricted - donor conditions apply',
                'reporting_required': True,
                'audit_required': True
            },
            'own_revenue_funds': {
                'code': 'OR',
                'name': 'Own Revenue Funds',
                'description': 'Funds generated by the entity through its own revenue-generating activities',
                'restrictions': 'Moderately restricted - must follow revenue generation rules',
                'reporting_required': True,
                'audit_required': True
            },
            'trading_funds': {
                'code': 'TF',
                'name': 'Trading Funds',
                'description': 'Funds generated through trading activities',
                'restrictions': 'Low restrictions - can be used for operational activities',
                'reporting_required': True,
                'audit_required': True
            },
            'capital_funds': {
                'code': 'CF',
                'name': 'Capital Funds',
                'description': 'Funds for capital expenditures and long-term investments',
                'restrictions': 'Highly restricted - capital expenditure only',
                'reporting_required': True,
                'audit_required': True
            },
            'contingency_funds': {
                'code': 'CT',
                'name': 'Contingency Funds',
                'description': 'Funds set aside for emergencies and unexpected events',
                'restrictions': 'Highly restricted - emergency use only',
                'reporting_required': True,
                'audit_required': True
            }
        }
    
    def _initialize_department_structure(self) -> Dict[str, Any]:
        """Initialize department structure for segment reporting"""
        return {
            'administration': {
                'code': 'ADM',
                'name': 'Administration',
                'description': 'General administrative and management functions',
                'cost_center': 'CC-001'
            },
            'finance': {
                'code': 'FIN',
                'name': 'Finance',
                'description': 'Financial management and accounting functions',
                'cost_center': 'CC-002'
            },
            'human_resources': {
                'code': 'HR',
                'name': 'Human Resources',
                'description': 'Personnel management and HR functions',
                'cost_center': 'CC-003'
            },
            'operations': {
                'code': 'OPS',
                'name': 'Operations',
                'description': 'Core operational and service delivery functions',
                'cost_center': 'CC-004'
            },
            'it_services': {
                'code': 'IT',
                'name': 'IT Services',
                'description': 'Information technology and digital services',
                'cost_center': 'CC-005'
            },
            'procurement': {
                'code': 'PUR',
                'name': 'Procurement',
                'description': 'Purchasing and supply chain management',
                'cost_center': 'CC-006'
            },
            'legal_services': {
                'code': 'LEG',
                'name': 'Legal Services',
                'description': 'Legal compliance and advisory services',
                'cost_center': 'CC-007'
            },
            'internal_audit': {
                'code': 'IA',
                'name': 'Internal Audit',
                'description': 'Internal audit and compliance functions',
                'cost_center': 'CC-008'
            }
        }
    
    def _initialize_function_structure(self) -> Dict[str, Any]:
        """Initialize function structure for segment reporting"""
        return {
            'policy_governance': {
                'code': 'PG',
                'name': 'Policy & Governance',
                'description': 'Policy development, governance, and oversight functions',
                'nature': 'strategic'
            },
            'service_delivery': {
                'code': 'SD',
                'name': 'Service Delivery',
                'description': 'Direct service delivery to citizens and stakeholders',
                'nature': 'operational'
            },
            'support_services': {
                'code': 'SS',
                'name': 'Support Services',
                'description': 'Administrative and support functions for service delivery',
                'nature': 'operational'
            },
            'infrastructure': {
                'code': 'INF',
                'name': 'Infrastructure',
                'description': 'Physical infrastructure and facilities management',
                'nature': 'operational'
            },
            'financial_management': {
                'code': 'FM',
                'name': 'Financial Management',
                'description': 'Financial planning, accounting, and reporting functions',
                'nature': 'operational'
            },
            'human_capital': {
                'code': 'HC',
                'name': 'Human Capital',
                'description': 'Human resources, training, and development functions',
                'nature': 'operational'
            },
            'compliance_monitoring': {
                'code': 'CM',
                'name': 'Compliance & Monitoring',
                'description': 'Regulatory compliance and performance monitoring',
                'nature': 'operational'
            },
            'research_development': {
                'code': 'RD',
                'name': 'Research & Development',
                'description': 'Research, innovation, and development functions',
                'nature': 'strategic'
            }
        }
    
    def apply_fund_tags(self, trial_balance_data: pd.DataFrame) -> pd.DataFrame:
        """Apply fund tags to trial balance data"""
        tagged_data = trial_balance_data.copy()
        
        # Initialize fund tag columns
        tagged_data['fund_code'] = ''
        tagged_data['fund_name'] = ''
        tagged_data['fund_restriction'] = ''
        tagged_data['fund_reporting_required'] = False
        
        # Apply fund tags based on account codes and descriptions
        for index, row in tagged_data.iterrows():
            account_code = str(row.get('Account Code', ''))
            account_desc = str(row.get('Account Description', '')).lower()
            
            fund_tag = self._determine_fund_tag(account_code, account_desc)
            tagged_data.at[index, 'fund_code'] = fund_tag['code']
            tagged_data.at[index, 'fund_name'] = fund_tag['name']
            tagged_data.at[index, 'fund_restriction'] = fund_tag['restrictions']
            tagged_data.at[index, 'fund_reporting_required'] = fund_tag['reporting_required']
        
        return tagged_data
    
    def _determine_fund_tag(self, account_code: str, account_desc: str) -> Dict[str, str]:
        """Determine fund tag based on account code and description"""
        account_code = account_code.zfill(4)
        
        # Government funds - typically revenue from government sources
        if account_code.startswith('4') and any(keyword in account_desc for keyword in ['government', 'grant', 'subsidy', 'tax']):
            return self.fund_structure['government_funds']
        
        # Donor funds - typically restricted revenue
        elif account_code.startswith('4') and any(keyword in account_desc for keyword in ['donor', 'funding', 'aid', 'sponsor']):
            return self.fund_structure['donor_funds']
        
        # Own revenue - general revenue generation
        elif account_code.startswith('4'):
            return self.fund_structure['own_revenue_funds']
        
        # Capital funds - asset purchases and capital expenditure
        elif account_code.startswith('1') and any(keyword in account_desc for keyword in ['capital', 'asset', 'equipment', 'investment']):
            return self.fund_structure['capital_funds']
        
        # Trading funds - operational income
        elif account_code.startswith('4') and any(keyword in account_desc for keyword in ['trading', 'sales', 'commercial']):
            return self.fund_structure['trading_funds']
        
        # Contingency funds - reserves and provisions
        elif account_code.startswith('2') and any(keyword in account_desc for keyword in ['contingency', 'reserve', 'provision', 'emergency']):
            return self.fund_structure['contingency_funds']
        
        # Default to own revenue for unspecified
        else:
            return self.fund_structure['own_revenue_funds']
    
    def apply_department_tags(self, trial_balance_data: pd.DataFrame) -> pd.DataFrame:
        """Apply department tags to trial balance data"""
        tagged_data = trial_balance_data.copy()
        
        # Initialize department tag columns
        tagged_data['department_code'] = ''
        tagged_data['department_name'] = ''
        tagged_data['cost_center'] = ''
        
        # Apply department tags based on account codes and descriptions
        for index, row in tagged_data.iterrows():
            account_code = str(row.get('Account Code', ''))
            account_desc = str(row.get('Account Description', '')).lower()
            
            dept_tag = self._determine_department_tag(account_code, account_desc)
            tagged_data.at[index, 'department_code'] = dept_tag['code']
            tagged_data.at[index, 'department_name'] = dept_tag['name']
            tagged_data.at[index, 'cost_center'] = dept_tag['cost_center']
        
        return tagged_data
    
    def _determine_department_tag(self, account_code: str, account_desc: str) -> Dict[str, str]:
        """Determine department tag based on account code and description"""
        account_code = account_code.zfill(4)
        
        # Administration - management and admin functions
        if any(keyword in account_desc for keyword in ['admin', 'management', 'executive', 'board', 'director']):
            return self.department_structure['administration']
        
        # Finance - financial functions
        elif any(keyword in account_desc for keyword in ['finance', 'accounting', 'treasury', 'financial', 'budget', 'audit']):
            return self.department_structure['finance']
        
        # Human Resources - personnel functions
        elif any(keyword in account_desc for keyword in ['salary', 'wage', 'employee', 'personnel', 'hr', 'human', 'training', 'benefit']):
            return self.department_structure['human_resources']
        
        # Operations - service delivery
        elif any(keyword in account_desc for keyword in ['operations', 'service', 'delivery', 'maintenance', 'operational']):
            return self.department_structure['operations']
        
        # IT Services - technology functions
        elif any(keyword in account_desc for keyword in ['it', 'technology', 'software', 'hardware', 'system', 'digital', 'computer']):
            return self.department_structure['it_services']
        
        # Procurement - purchasing functions
        elif any(keyword in account_desc for keyword in ['procurement', 'purchasing', 'supply', 'vendor', 'contract']):
            return self.department_structure['procurement']
        
        # Legal Services - legal functions
        elif any(keyword in account_desc for keyword in ['legal', 'compliance', 'regulatory', 'attorney', 'counsel']):
            return self.department_structure['legal_services']
        
        # Internal Audit - audit functions
        elif any(keyword in account_desc for keyword in ['internal audit', 'compliance', 'review', 'inspection']):
            return self.department_structure['internal_audit']
        
        # Default based on account code ranges
        elif account_code.startswith('6') or account_code.startswith('7'):
            return self.department_structure['operations']
        elif account_code.startswith('5'):
            return self.department_structure['human_resources']
        else:
            return self.department_structure['administration']
    
    def apply_function_tags(self, trial_balance_data: pd.DataFrame) -> pd.DataFrame:
        """Apply function tags to trial balance data"""
        tagged_data = trial_balance_data.copy()
        
        # Initialize function tag columns
        tagged_data['function_code'] = ''
        tagged_data['function_name'] = ''
        tagged_data['function_nature'] = ''
        
        # Apply function tags based on account codes and descriptions
        for index, row in tagged_data.iterrows():
            account_code = str(row.get('Account Code', ''))
            account_desc = str(row.get('Account Description', '')).lower()
            
            func_tag = self._determine_function_tag(account_code, account_desc)
            tagged_data.at[index, 'function_code'] = func_tag['code']
            tagged_data.at[index, 'function_name'] = func_tag['name']
            tagged_data.at[index, 'function_nature'] = func_tag['nature']
        
        return tagged_data
    
    def _determine_function_tag(self, account_code: str, account_desc: str) -> Dict[str, str]:
        """Determine function tag based on account code and description"""
        account_code = account_code.zfill(4)
        
        # Policy & Governance
        if any(keyword in account_desc for keyword in ['policy', 'governance', 'strategy', 'planning', 'oversight', 'board', 'council']):
            return self.function_structure['policy_governance']
        
        # Service Delivery
        elif any(keyword in account_desc for keyword in ['service', 'delivery', 'citizen', 'customer', 'public', 'community']):
            return self.function_structure['service_delivery']
        
        # Support Services
        elif any(keyword in account_desc for keyword in ['support', 'administrative', 'back office', 'coordination']):
            return self.function_structure['support_services']
        
        # Infrastructure
        elif any(keyword in account_desc for keyword in ['infrastructure', 'facility', 'building', 'equipment', 'maintenance', 'utilities']):
            return self.function_structure['infrastructure']
        
        # Financial Management
        elif any(keyword in account_desc for keyword in ['finance', 'accounting', 'treasury', 'financial', 'budget', 'cash', 'investment']):
            return self.function_structure['financial_management']
        
        # Human Capital
        elif any(keyword in account_desc for keyword in ['human', 'personnel', 'employee', 'training', 'development', 'hr', 'benefit']):
            return self.function_structure['human_capital']
        
        # Compliance & Monitoring
        elif any(keyword in account_desc for keyword in ['compliance', 'monitoring', 'regulatory', 'audit', 'quality', 'risk']):
            return self.function_structure['compliance_monitoring']
        
        # Research & Development
        elif any(keyword in account_desc for keyword in ['research', 'development', 'innovation', 'rd', 'technology', 'study']):
            return self.function_structure['research_development']
        
        # Default based on account code ranges
        elif account_code.startswith('4'):
            return self.function_structure['service_delivery']
        elif account_code.startswith('5'):
            return self.function_structure['service_delivery']
        elif account_code.startswith('6') or account_code.startswith('7'):
            return self.function_structure['support_services']
        else:
            return self.function_structure['policy_governance']
    
    def generate_segment_report(self, tagged_data: pd.DataFrame) -> Dict[str, Any]:
        """Generate GRAP 18 segment report"""
        segment_report = {
            'report_id': f"SEG_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            'generated_at': datetime.now().isoformat(),
            'report_type': 'GRAP_18_SEGMENT_REPORT',
            'fund_analysis': self._analyze_fund_segments(tagged_data),
            'department_analysis': self._analyze_department_segments(tagged_data),
            'function_analysis': self._analyze_function_segments(tagged_data),
            'cross_segment_analysis': self._analyze_cross_segments(tagged_data),
            'compliance_metrics': self._calculate_segment_compliance(tagged_data)
        }
        
        return segment_report
    
    def _analyze_fund_segments(self, tagged_data: pd.DataFrame) -> Dict[str, Any]:
        """Analyze fund segments"""
        fund_analysis = {}
        
        # Group by fund type
        fund_groups = tagged_data.groupby('fund_code')['Net Balance'].sum().abs()
        
        for fund_code, total_amount in fund_groups.items():
            if fund_code and total_amount > 0:
                fund_info = self.fund_structure.get(fund_code, {})
                fund_analysis[fund_code] = {
                    'fund_name': fund_info.get('name', 'Unknown Fund'),
                    'total_amount': total_amount,
                    'percentage_of_total': (total_amount / fund_groups.sum()) * 100,
                    'restriction_level': fund_info.get('restrictions', 'Unknown'),
                    'reporting_required': fund_info.get('reporting_required', False),
                    'audit_required': fund_info.get('audit_required', False)
                }
        
        return fund_analysis
    
    def _analyze_department_segments(self, tagged_data: pd.DataFrame) -> Dict[str, Any]:
        """Analyze department segments"""
        dept_analysis = {}
        
        # Group by department
        dept_groups = tagged_data.groupby('department_code')['Net Balance'].sum().abs()
        
        for dept_code, total_amount in dept_groups.items():
            if dept_code and total_amount > 0:
                dept_info = self.department_structure.get(dept_code, {})
                dept_analysis[dept_code] = {
                    'department_name': dept_info.get('name', 'Unknown Department'),
                    'cost_center': dept_info.get('cost_center', 'Unknown'),
                    'total_amount': total_amount,
                    'percentage_of_total': (total_amount / dept_groups.sum()) * 100
                }
        
        return dept_analysis
    
    def _analyze_function_segments(self, tagged_data: pd.DataFrame) -> Dict[str, Any]:
        """Analyze function segments"""
        func_analysis = {}
        
        # Group by function
        func_groups = tagged_data.groupby('function_code')['Net Balance'].sum().abs()
        
        for func_code, total_amount in func_groups.items():
            if func_code and total_amount > 0:
                func_info = self.function_structure.get(func_code, {})
                func_analysis[func_code] = {
                    'function_name': func_info.get('name', 'Unknown Function'),
                    'nature': func_info.get('nature', 'Unknown'),
                    'total_amount': total_amount,
                    'percentage_of_total': (total_amount / func_groups.sum()) * 100
                }
        
        return func_analysis
    
    def _analyze_cross_segments(self, tagged_data: pd.DataFrame) -> Dict[str, Any]:
        """Analyze cross-segment relationships"""
        cross_analysis = {
            'fund_by_department': {},
            'function_by_fund': {},
            'department_by_function': {},
            'top_combinations': []
        }
        
        # Fund by Department
        fund_dept_pivot = tagged_data.groupby(['fund_code', 'department_code'])['Net Balance'].sum().abs()
        for (fund_code, dept_code), amount in fund_dept_pivot.items():
            if amount > 0:
                if fund_code not in cross_analysis['fund_by_department']:
                    cross_analysis['fund_by_department'][fund_code] = {}
                cross_analysis['fund_by_department'][fund_code][dept_code] = amount
        
        # Function by Fund
        func_fund_pivot = tagged_data.groupby(['function_code', 'fund_code'])['Net Balance'].sum().abs()
        for (func_code, fund_code), amount in func_fund_pivot.items():
            if amount > 0:
                if func_code not in cross_analysis['function_by_fund']:
                    cross_analysis['function_by_fund'][func_code] = {}
                cross_analysis['function_by_fund'][func_code][fund_code] = amount
        
        # Department by Function
        dept_func_pivot = tagged_data.groupby(['department_code', 'function_code'])['Net Balance'].sum().abs()
        for (dept_code, func_code), amount in dept_func_pivot.items():
            if amount > 0:
                if dept_code not in cross_analysis['department_by_function']:
                    cross_analysis['department_by_function'][dept_code] = {}
                cross_analysis['department_by_function'][dept_code][func_code] = amount
        
        # Top combinations
        all_combinations = []
        for (fund_code, dept_code), amount in fund_dept_pivot.items():
            if amount > 0:
                all_combinations.append({
                    'combination': f"{fund_code}-{dept_code}",
                    'amount': amount,
                    'fund_name': self.fund_structure.get(fund_code, {}).get('name', 'Unknown'),
                    'department_name': self.department_structure.get(dept_code, {}).get('name', 'Unknown')
                })
        
        # Sort by amount and get top 10
        cross_analysis['top_combinations'] = sorted(all_combinations, key=lambda x: x['amount'], reverse=True)[:10]
        
        return cross_analysis
    
    def _calculate_segment_compliance(self, tagged_data: pd.DataFrame) -> Dict[str, Any]:
        """Calculate segment reporting compliance metrics"""
        total_records = len(tagged_data)
        tagged_records = len(tagged_data[
            (tagged_data['fund_code'] != '') & 
            (tagged_data['department_code'] != '') & 
            (tagged_data['function_code'] != '')
        ])
        
        compliance_metrics = {
            'total_records': total_records,
            'tagged_records': tagged_records,
            'tagging_coverage': (tagged_records / total_records) * 100 if total_records > 0 else 0,
            'fund_types_covered': len(tagged_data['fund_code'].unique()),
            'department_types_covered': len(tagged_data['department_code'].unique()),
            'function_types_covered': len(tagged_data['function_code'].unique()),
            'compliance_score': 0.0,
            'risk_level': 'LOW'
        }
        
        # Calculate compliance score
        if compliance_metrics['tagging_coverage'] >= 95:
            compliance_metrics['compliance_score'] = 100.0
            compliance_metrics['risk_level'] = 'LOW'
        elif compliance_metrics['tagging_coverage'] >= 80:
            compliance_metrics['compliance_score'] = 85.0
            compliance_metrics['risk_level'] = 'MEDIUM'
        else:
            compliance_metrics['compliance_score'] = 70.0
            compliance_metrics['risk_level'] = 'HIGH'
        
        return compliance_metrics
